version: 2
updates:
- package-ecosystem: "github-actions" 
  directory: "/"
  # target-branch: "feature/dependabot"
  schedule: 
    interval: "daily"
    time: "07:29"
registries:
  github:
    type: git
    url: https://github.com/mayankmj/repo-2
    username: mayankmj
    password: 02122002Mj@
    
    
