version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: mayankmj
    password: ${{secrets.PAT_DEPENDABOT}}
updates:
  - package-ecosystem: "github-actions" 
    directory: "/"
    # target-branch: "feature/dependabot"
    registries: "*"
    schedule: 
      interval: "daily"
      time: "07:54"



    
    
