name: Workflow_01
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Your existing workflow steps go here

  trigger-workflow02:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow_02
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: mayankmj/repo-2
          event-type: trigger-workflow02
          client-payload: {}
