name: Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  call-reusable-workflow:
    uses: mayankmj/repo-2/.github/workflows/main.yml@main
    with:
      event-type: trigger-workflow
      token: ${{ secrets.ACTION_KEY }}
