name: Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install composite run steps action
        run: npm install -g composite-run-steps@latest

      - name: Call Reusable Workflow
        run: composite-run-steps --file mayankmj/repo-2/.github/workflows/main.yml@main --inputs target_service=${{ github.event.inputs.target_service }} target_version=${{ github.event.inputs.target_version }}
