name: Workflow_01
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Your existing workflow steps 

      # Add a step to trigger the workflow in another repository
      - name: Trigger Workflow_02
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/mayankmj/repo-2/actions/workflows/workflow_02.yml/dispatches \
            -d '{"ref":"main"}'
