name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repo-2 workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTION_KEY }}
          repository: mayankmj/repo-2
          event-type: trigger-workflow
