name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repo-2 workflow
        uses: actions/checkout@v2
      - name: Call the reusable workflow in repo-2
        uses: ./.github/workflows/main.yml
        with:
          token: ${{ secrets.ACTION_KEY }}
          repository: mayankmj/repo-2
          event-type: trigger-workflow
