name: Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repo-2 workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTION_KEY }}
          script: |
            const { Octokit } = require("@octokit/core");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            const response = await octokit.request('POST /repos/:mayankmj/:repo-2/dispatches', {
              owner: 'mayankmj',
              repo: 'repo-2',
              event_type: 'trigger-workflow'
            });

            console.log(response.status);
