name: Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repo-2 workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: 'mayankmj',
              repo: 'repo-2',
              event_type: 'trigger-workflow',
              # client_payload: {
              #   target_service: '${{ github.event.inputs.target_service }}',
              #   target_version: '${{ github.event.inputs.target_version }}'
              # }
            })
