name: Scheduler

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  Scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test file
        run: echo hello > test.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: test.txt

      - name: Set up Git user
        run: |
          git config --global user.name 'mayankmj'
          git config --global user.email 'mayankjohari877@gmail.com'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit test file
          file_pattern: test.txt

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://mayankmj:${{ secrets.ACTION_KEY }}@github.com/mayankmj/repo-1.git
          git push origin main
